name: Remove old reports
on:
    schedule:
        - cron: 0 0 * * *
    workflow_dispatch:
        inputs:
            versionType:
                type: choice
                description: Some choice
                required: true
                options:
                    - patch
                    - minor
                    - major
permissions:
    pull-requests: write
jobs:
    collect:
        name: Remove old reports
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Remove reports
              uses: gemini-testing/gh-actions-reports-ttl-cleaner@824850ce63565669d5d4e0f02610dad4b49526b5
              with:
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
