name: Remove old reports
on:
    push:
        branches: [master]
    workflow_dispatch:

jobs:
    collect:
        name: Remove old reports
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: gh-pages
                  fetch-depth: 0
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Remove reports
              uses: gemini-testing/gh-actions-reports-ttl-cleaner@TESTPLANE-466.reports_ttl_cleaner

