name: Remove old reports
on:
    push:
        branches: [master]
    schedule:
        - cron: 0 0 * * *
    workflow_dispatch:
        inputs:
            versionType:
                type: choice
                description: Some choice
                required: true
                options:
                    - patch
                    - minor
                    - major
jobs:
    collect:
        name: Remove old reports
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: gh-pages
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Remove reports
              uses: gemini-testing/gh-actions-reports-ttl-cleaner@8fba652698e96da3d134c816cd90e469198357fa

