name: Node CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
            node-version: 18.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm deps
        run: npm install

      - name: Setup env
        run: |
          REPORT_PREFIX=testplane-reports
          REPORT_DATE=$(date '+%y-%m-%d')
          echo "REPORT_PATH=$REPORT_PREFIX/$REPORT_DATE/${{ github.run_id }}/${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "TESTPLANE_BROWSERS_CACHE_KEY=$(npx testplane list-browsers --type tags --format plain | sha256sum | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Cache Testplane dependencies
        uses: actions/cache@v3
        with:
          path: ~/.testplane
          key: ${{ runner.os }}-testplane-browsers-${{ env.TESTPLANE_BROWSERS_CACHE_KEY }}

      - name: Install Testplane deps
        run: npx testplane install-deps

      - name: Run Testplane
        run: npx testplane

      - name: Prepare to deploy report
        if: always()
        run: mkdir -p $REPORT_PATH && mv testplane-report/* $REPORT_PATH

      - name: Deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.REPORT_PATH }}
          destination_dir: ${{ env.REPORT_PATH }}
          keep_files: true
      - name: Comment PR with link to Testplane HTML report
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
            message: |
                ### :x: Testplane run failed

                Testplane HTML-report is available at https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.REPORT_PATH }}
            comment-tag: testplane_html_report_link

